### ISSUE TITLE
I got bug when i merge multiple schema file

### ISSUE THREAD

**Issue by Anhdao153** [DavidHancu/prisma-util#4]
<img width="1440" alt="Screen Shot 2022-10-06 at 21 46 20" src="https://user-images.githubusercontent.com/87293423/194344264-14bf7529-4c4f-460e-bf16-b29ba38dcd32.png">

I'm following the tutorial, but when i merged schema, i got this bug. And i searched in a few day, i still got nothing.
can some advise for me?

**Comment by DavidHancu** [comment]
Hi @Anhdao153, can you show your configuration file?

**Comment by Anhdao153** [comment]
Here is my configuration file
<img width="1440" alt="Screen Shot 2022-10-08 at 19 01 14" src="https://user-images.githubusercontent.com/87293423/194706413-0eefd191-7ac3-479c-a231-9b9649a2d74b.png">

Post entity
<img width="1440" alt="Screen Shot 2022-10-08 at 19 01 24" src="https://user-images.githubusercontent.com/87293423/194706421-adeb54ca-71c4-488b-b3fc-a15079b71352.png">

User entity
<img width="1440" alt="Screen Shot 2022-10-08 at 19 01 52" src="https://user-images.githubusercontent.com/87293423/194706439-d5ced618-e976-49c7-bf07-8b4ba5703239.png">

**Comment by DavidHancu** [comment]
Hi @Anhdao153!

I can see that you've made a typo in your configuration file. Please replace your relations with this and retry:
```json
"relations": {
    "./src/models/core/Post.prisma:Post.user": "./src/models/core/User.prisma:User"
}
```

**Comment by Anhdao153** [comment]
Hi @DavidHancu !
I tried, but unfortunately it didn't work
I still don't know why, please help 
SOS :((
![Screen Shot 2022-10-12 at 22 42 00](https://user-images.githubusercontent.com/87293423/195387980-4d23c461-3fbd-41ba-a32d-6569f135b37f.png)

**Comment by Anhdao153** [comment]
@DavidHancu Hi. after a few days from the last message i still can't resolve this bug, would you mind help me to fix it, please?

**Comment by DavidHancu** [comment]
Hi @Anhdao153, this is not an issue with Prisma Util but with your configuration, as I can't replicate this issue in Prisma Util v1.3.0.

**Comment by DavidHancu** [comment]
Closed due to inactivity.
